package com.invensense.model.workrelations;

public class F_CONTRACT_VO {

	private String ASSIGNMENT_ID;
	private String BUSINESS_GROUP_ID;
	private String CONTRACT_ID;
	private String EFFECTIVE_START_DATE;
	private String EFFECTIVE_END_DATE;
	private String CONTRACTUAL_JOB_TITLE;
	private String DESCRIPTION;
	private String DOC_STATUS;
	private String DOC_STATUS_CHANGE_DATE;
	private String DURATION;
	private String DURATION_UNITS;
	private String EXTENSION_PERIOD;
	private String EXTENSION_PERIOD_UNITS;
	private String NUMBER_OF_EXTENSIONS;
	private String PERSON_ID;
	private String CONTRACT_TYPE;
	private String WORK_TERMS_TYPE;
	private String END_REASON;
	private String EXTENSION_REASON;
	private String PARTIES;
	private String REFERENCE;
	private String START_REASON;
	private String STATUS;
	private String STATUS_REASON;
	
	public F_CONTRACT_VO(String aSSIGNMENT_ID, String bUSINESS_GROUP_ID, String cONTRACT_ID,
			String eFFECTIVE_START_DATE, String eFFECTIVE_END_DATE, String cONTRACTUAL_JOB_TITLE, String dESCRIPTION,
			String dOC_STATUS, String dOC_STATUS_CHANGE_DATE, String dURATION, String dURATION_UNITS,
			String eXTENSION_PERIOD, String eXTENSION_PERIOD_UNITS, String nUMBER_OF_EXTENSIONS, String pERSON_ID,
			String cONTRACT_TYPE, String wORK_TERMS_TYPE, String eND_REASON, String eXTENSION_REASON, String pARTIES,
			String rEFERENCE, String sTART_REASON, String sTATUS, String sTATUS_REASON) {
		super();
		ASSIGNMENT_ID = aSSIGNMENT_ID;
		BUSINESS_GROUP_ID = bUSINESS_GROUP_ID;
		CONTRACT_ID = cONTRACT_ID;
		EFFECTIVE_START_DATE = eFFECTIVE_START_DATE;
		EFFECTIVE_END_DATE = eFFECTIVE_END_DATE;
		CONTRACTUAL_JOB_TITLE = cONTRACTUAL_JOB_TITLE;
		DESCRIPTION = dESCRIPTION;
		DOC_STATUS = dOC_STATUS;
		DOC_STATUS_CHANGE_DATE = dOC_STATUS_CHANGE_DATE;
		DURATION = dURATION;
		DURATION_UNITS = dURATION_UNITS;
		EXTENSION_PERIOD = eXTENSION_PERIOD;
		EXTENSION_PERIOD_UNITS = eXTENSION_PERIOD_UNITS;
		NUMBER_OF_EXTENSIONS = nUMBER_OF_EXTENSIONS;
		PERSON_ID = pERSON_ID;
		CONTRACT_TYPE = cONTRACT_TYPE;
		WORK_TERMS_TYPE = wORK_TERMS_TYPE;
		END_REASON = eND_REASON;
		EXTENSION_REASON = eXTENSION_REASON;
		PARTIES = pARTIES;
		REFERENCE = rEFERENCE;
		START_REASON = sTART_REASON;
		STATUS = sTATUS;
		STATUS_REASON = sTATUS_REASON;
	}

	
	public String toDelimitedString() {
		return ASSIGNMENT_ID + "|" + BUSINESS_GROUP_ID + "|" + CONTRACT_ID + "|" + EFFECTIVE_START_DATE + "|"
				+ EFFECTIVE_END_DATE + "|" + CONTRACTUAL_JOB_TITLE + "|" + DESCRIPTION + "|" + DOC_STATUS + "|"
				+ DOC_STATUS_CHANGE_DATE + "|" + DURATION + "|" + DURATION_UNITS + "|" + EXTENSION_PERIOD + "|"
				+ EXTENSION_PERIOD_UNITS + "|" + NUMBER_OF_EXTENSIONS + "|" + PERSON_ID + "|" + CONTRACT_TYPE + "|"
				+ WORK_TERMS_TYPE + "|" + END_REASON + "|" + EXTENSION_REASON + "|" + PARTIES + "|" + REFERENCE + "|"
				+ START_REASON + "|" + STATUS + "|" + STATUS_REASON;
	}
	
	
	
}
