
package com.oracle.xmlns.apps.hcm.common.batchloader.core.loaderintegrationservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import org.apache.log4j.Logger;

import com.invensense.impl.taleo.CreatePersonFiles;
import com.invensense.utils.HCMConstants;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LoaderIntegrationService", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/batchLoader/core/loaderIntegrationService/", wsdlLocation = "https://hbbc-test.hcm.us2.oraclecloud.com:443//hcmCommonBatchLoader/LoaderIntegrationService?wsdl")
public class LoaderIntegrationService_Service
    extends Service
{

    private final static URL LOADERINTEGRATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException LOADERINTEGRATIONSERVICE_EXCEPTION;
    private final static QName LOADERINTEGRATIONSERVICE_QNAME = new QName("http://xmlns.oracle.com/apps/hcm/common/batchLoader/core/loaderIntegrationService/", "LoaderIntegrationService");
    private static Logger logger = Logger.getLogger(LoaderIntegrationService_Service.class);
    static {
        URL url = null;
        WebServiceException e = null;
        try {
            logger.debug("HCM URL : "+HCMConstants.getHcmLoaderWSDLUrl());
            url = new URL(HCMConstants.getHcmLoaderWSDLUrl());
           // url = new URL(
           	//	"https://hbbc-test.hcm.us2.oraclecloud.com:443//hcmCommonBatchLoader/LoaderIntegrationService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LOADERINTEGRATIONSERVICE_WSDL_LOCATION = url;
        LOADERINTEGRATIONSERVICE_EXCEPTION = e;
    }

    public LoaderIntegrationService_Service() {
        super(__getWsdlLocation(), LOADERINTEGRATIONSERVICE_QNAME);
    }

    public LoaderIntegrationService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), LOADERINTEGRATIONSERVICE_QNAME, features);
    }

    public LoaderIntegrationService_Service(URL wsdlLocation) {
        super(wsdlLocation, LOADERINTEGRATIONSERVICE_QNAME);
    }

    public LoaderIntegrationService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LOADERINTEGRATIONSERVICE_QNAME, features);
    }

    public LoaderIntegrationService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LoaderIntegrationService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LoaderIntegrationService
     */
    @WebEndpoint(name = "LoaderIntegrationServiceSoapHttpPort")
    public LoaderIntegrationService getLoaderIntegrationServiceSoapHttpPort() {
        return super.getPort(new QName("http://xmlns.oracle.com/apps/hcm/common/batchLoader/core/loaderIntegrationService/", "LoaderIntegrationServiceSoapHttpPort"), LoaderIntegrationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LoaderIntegrationService
     */
    @WebEndpoint(name = "LoaderIntegrationServiceSoapHttpPort")
    public LoaderIntegrationService getLoaderIntegrationServiceSoapHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/apps/hcm/common/batchLoader/core/loaderIntegrationService/", "LoaderIntegrationServiceSoapHttpPort"), LoaderIntegrationService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LOADERINTEGRATIONSERVICE_EXCEPTION!= null) {
            throw LOADERINTEGRATIONSERVICE_EXCEPTION;
        }
        return LOADERINTEGRATIONSERVICE_WSDL_LOCATION;
    }

}
