
package com.oracle.xmlns.apps.hcm.common.batchloader.core.loaderintegrationservice;

import java.util.List;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LoaderIntegrationService", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/batchLoader/core/loaderIntegrationService/")
@XmlSeeAlso({
    com.oracle.xmlns.adf.svc.errors.ObjectFactory.class,
    com.oracle.xmlns.apps.hcm.common.batchloader.core.loaderintegrationservice.types.ObjectFactory.class,
    com.oracle.xmlns.oracleas.schema.oracle_fault_11_0.ObjectFactory.class,
    sdo.commonj.ObjectFactory.class,
    sdo.commonj.java.ObjectFactory.class
})
public interface LoaderIntegrationService {


    /**
     * 
     * @param batchName
     * @param businessObjectList
     * @param loadType
     * @param zipFileName
     * @param autoLoad
     * @return
     *     returns java.lang.String
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/hcm/common/batchLoader/core/loaderIntegrationService/submitBatch")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/batchLoader/core/loaderIntegrationService/types/")
    @RequestWrapper(localName = "submitBatch", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/batchLoader/core/loaderIntegrationService/types/", className = "com.oracle.xmlns.apps.hcm.common.batchloader.core.loaderintegrationservice.types.SubmitBatch")
    @ResponseWrapper(localName = "submitBatchResponse", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/batchLoader/core/loaderIntegrationService/types/", className = "com.oracle.xmlns.apps.hcm.common.batchloader.core.loaderintegrationservice.types.SubmitBatchResponse")
    public String submitBatch(
        @WebParam(name = "ZipFileName", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/batchLoader/core/loaderIntegrationService/types/")
        String zipFileName,
        @WebParam(name = "BusinessObjectList", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/batchLoader/core/loaderIntegrationService/types/")
        List<String> businessObjectList,
        @WebParam(name = "BatchName", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/batchLoader/core/loaderIntegrationService/types/")
        String batchName,
        @WebParam(name = "LoadType", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/batchLoader/core/loaderIntegrationService/types/")
        String loadType,
        @WebParam(name = "AutoLoad", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/batchLoader/core/loaderIntegrationService/types/")
        String autoLoad)
        throws ServiceException
    ;

    /**
     * 
     * @return
     *     returns java.lang.String
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/hcm/common/batchLoader/core/loaderIntegrationService/crossReferenceExtract")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/batchLoader/core/loaderIntegrationService/types/")
    @RequestWrapper(localName = "crossReferenceExtract", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/batchLoader/core/loaderIntegrationService/types/", className = "com.oracle.xmlns.apps.hcm.common.batchloader.core.loaderintegrationservice.types.CrossReferenceExtract")
    @ResponseWrapper(localName = "crossReferenceExtractResponse", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/batchLoader/core/loaderIntegrationService/types/", className = "com.oracle.xmlns.apps.hcm.common.batchloader.core.loaderintegrationservice.types.CrossReferenceExtractResponse")
    public String crossReferenceExtract()
        throws ServiceException
    ;

    /**
     * 
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/hcm/common/batchLoader/core/loaderIntegrationService/crossReferenceExtractAsync")
    @Oneway
    @RequestWrapper(localName = "crossReferenceExtractAsync", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/batchLoader/core/loaderIntegrationService/types/", className = "com.oracle.xmlns.apps.hcm.common.batchloader.core.loaderintegrationservice.types.CrossReferenceExtractAsync")
    public void crossReferenceExtractAsync();

    /**
     * 
     * @param batchName
     * @param businessObjectList
     * @param loadType
     * @param zipFileName
     * @param autoLoad
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/hcm/common/batchLoader/core/loaderIntegrationService/submitBatchAsync")
    @Oneway
    @RequestWrapper(localName = "submitBatchAsync", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/batchLoader/core/loaderIntegrationService/types/", className = "com.oracle.xmlns.apps.hcm.common.batchloader.core.loaderintegrationservice.types.SubmitBatchAsync")
    public void submitBatchAsync(
        @WebParam(name = "ZipFileName", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/batchLoader/core/loaderIntegrationService/types/")
        String zipFileName,
        @WebParam(name = "BusinessObjectList", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/batchLoader/core/loaderIntegrationService/types/")
        List<String> businessObjectList,
        @WebParam(name = "BatchName", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/batchLoader/core/loaderIntegrationService/types/")
        String batchName,
        @WebParam(name = "LoadType", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/batchLoader/core/loaderIntegrationService/types/")
        String loadType,
        @WebParam(name = "AutoLoad", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/batchLoader/core/loaderIntegrationService/types/")
        String autoLoad);

    /**
     * 
     * @param batchName
     * @param businessObjectList
     * @param loadType
     * @param zipFileName
     * @param autoLoad
     * @param encryptType
     * @return
     *     returns java.lang.String
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/hcm/common/batchLoader/core/loaderIntegrationService/submitEncryptedBatch")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/batchLoader/core/loaderIntegrationService/types/")
    @RequestWrapper(localName = "submitEncryptedBatch", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/batchLoader/core/loaderIntegrationService/types/", className = "com.oracle.xmlns.apps.hcm.common.batchloader.core.loaderintegrationservice.types.SubmitEncryptedBatch")
    @ResponseWrapper(localName = "submitEncryptedBatchResponse", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/batchLoader/core/loaderIntegrationService/types/", className = "com.oracle.xmlns.apps.hcm.common.batchloader.core.loaderintegrationservice.types.SubmitEncryptedBatchResponse")
    public String submitEncryptedBatch(
        @WebParam(name = "ZipFileName", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/batchLoader/core/loaderIntegrationService/types/")
        String zipFileName,
        @WebParam(name = "BusinessObjectList", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/batchLoader/core/loaderIntegrationService/types/")
        List<String> businessObjectList,
        @WebParam(name = "BatchName", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/batchLoader/core/loaderIntegrationService/types/")
        String batchName,
        @WebParam(name = "LoadType", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/batchLoader/core/loaderIntegrationService/types/")
        String loadType,
        @WebParam(name = "AutoLoad", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/batchLoader/core/loaderIntegrationService/types/")
        String autoLoad,
        @WebParam(name = "encryptType", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/batchLoader/core/loaderIntegrationService/types/")
        String encryptType)
        throws ServiceException
    ;

    /**
     * 
     * @param batchName
     * @param businessObjectList
     * @param loadType
     * @param zipFileName
     * @param autoLoad
     * @param encryptType
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/hcm/common/batchLoader/core/loaderIntegrationService/submitEncryptedBatchAsync")
    @Oneway
    @RequestWrapper(localName = "submitEncryptedBatchAsync", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/batchLoader/core/loaderIntegrationService/types/", className = "com.oracle.xmlns.apps.hcm.common.batchloader.core.loaderintegrationservice.types.SubmitEncryptedBatchAsync")
    public void submitEncryptedBatchAsync(
        @WebParam(name = "ZipFileName", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/batchLoader/core/loaderIntegrationService/types/")
        String zipFileName,
        @WebParam(name = "BusinessObjectList", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/batchLoader/core/loaderIntegrationService/types/")
        List<String> businessObjectList,
        @WebParam(name = "BatchName", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/batchLoader/core/loaderIntegrationService/types/")
        String batchName,
        @WebParam(name = "LoadType", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/batchLoader/core/loaderIntegrationService/types/")
        String loadType,
        @WebParam(name = "AutoLoad", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/batchLoader/core/loaderIntegrationService/types/")
        String autoLoad,
        @WebParam(name = "encryptType", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/batchLoader/core/loaderIntegrationService/types/")
        String encryptType);

}
