package com.invensense.model.person;

public class F_PERSON_LEGISLATIVE_DATA_VO {
	private String PERSON_LEGISLATIVE_ID;
	private String EFFECTIVE_START_DATE;
	private String EFFECTIVE_END_DATE;
	private String BUSINESS_GROUP_ID;
	private String PERSON_ID;
	private String LEGISLATION_CODE;
	private String HIGHEST_EDUCATION_LEVEL;
	private String MARITAL_STATUS;
	private String MARITAL_STATUS_DATE;
	private String SEX;
	private String ATTRIBUTE_CATEGORY;
	private String ATTRIBUTE1;
	private String ATTRIBUTE2;
	private String ATTRIBUTE3;
	private String ATTRIBUTE4;
	private String ATTRIBUTE5;
	private String ATTRIBUTE6;
	private String ATTRIBUTE7;
	private String ATTRIBUTE8;
	private String ATTRIBUTE9;
	private String ATTRIBUTE10;
	private String ATTRIBUTE11;
	private String ATTRIBUTE12;
	private String ATTRIBUTE13;
	private String ATTRIBUTE14;
	private String ATTRIBUTE15;
	private String ATTRIBUTE16;
	private String ATTRIBUTE17;
	private String ATTRIBUTE18;
	private String ATTRIBUTE19;
	private String ATTRIBUTE20;
	private String ATTRIBUTE21;
	private String ATTRIBUTE22;
	private String ATTRIBUTE23;
	private String ATTRIBUTE24;
	private String ATTRIBUTE25;
	private String ATTRIBUTE26;
	private String ATTRIBUTE27;
	private String ATTRIBUTE28;
	private String ATTRIBUTE29;
	private String ATTRIBUTE30;
	private String PER_INFROMATION_CATEGORY;
	private String PER_INFORMATION1;
	private String PER_INFORMATION2;
	private String PER_INFORMATION3;
	private String PER_INFORMATION4;
	private String PER_INFORMATION5;
	private String PER_INFORMATION6;
	private String PER_INFORMATION7;
	private String PER_INFORMATION8;
	private String PER_INFORMATION9;
	private String PER_INFORMATION10;
	private String PER_INFORMATION11;
	private String PER_INFORMATION12;
	private String PER_INFORMATION13;
	private String PER_INFORMATION14;
	private String PER_INFORMATION15;
	private String PER_INFORMATION16;
	private String PER_INFORMATION17;
	private String PER_INFORMATION18;
	private String PER_INFORMATION19;
	private String PER_INFORMATION20;
	private String PER_INFORMATION21;
	private String PER_INFORMATION22;
	private String PER_INFORMATION23;
	private String PER_INFORMATION24;
	private String PER_INFORMATION25;
	private String PER_INFORMATION26;
	private String PER_INFORMATION27;
	private String PER_INFORMATION28;
	private String PER_INFORMATION29;
	private String PER_INFORMATION30;
	private String PER_INFORMATION_DATE1;
	private String PER_INFORMATION_DATE2;
	private String PER_INFORMATION_DATE3;
	private String PER_INFORMATION_DATE4;
	private String PER_INFORMATION_DATE5;
	private String PER_INFORMATION_DATE6;
	private String PER_INFORMATION_DATE7;
	private String PER_INFORMATION_DATE8;
	private String PER_INFORMATION_DATE9;
	private String PER_INFORMATION_DATE10;
	private String PER_INFORMATION_DATE11;
	private String PER_INFORMATION_DATE12;
	private String PER_INFORMATION_DATE13;
	private String PER_INFORMATION_DATE14;
	private String PER_INFORMATION_DATE15;
	private String PER_INFORMATION_NUMBER1;
	private String PER_INFORMATION_NUMBER2;
	private String PER_INFORMATION_NUMBER3;
	private String PER_INFORMATION_NUMBER4;
	private String PER_INFORMATION_NUMBER5;
	private String PER_INFORMATION_NUMBER6;
	private String PER_INFORMATION_NUMBER7;
	private String PER_INFORMATION_NUMBER8;
	private String PER_INFORMATION_NUMBER9;
	private String PER_INFORMATION_NUMBER10;
	private String PER_INFORMATION_NUMBER11;
	private String PER_INFORMATION_NUMBER12;
	private String PER_INFORMATION_NUMBER13;
	private String PER_INFORMATION_NUMBER14;
	private String PER_INFORMATION_NUMBER15;
	private String PER_INFORMATION_NUMBER16;
	private String PER_INFORMATION_NUMBER17;
	private String PER_INFORMATION_NUMBER18;
	private String PER_INFORMATION_NUMBER19;
	private String PER_INFORMATION_NUMBER20;
	private String FT_ALTERNATE_REC;
	private String FT_ALTERNATE_KEY;

	public F_PERSON_LEGISLATIVE_DATA_VO() {

	}

	
	
	
	public String toDelimitedString() {
		return PERSON_LEGISLATIVE_ID + "|" + EFFECTIVE_START_DATE + "|" + EFFECTIVE_END_DATE + "|"
				+ BUSINESS_GROUP_ID + "|" + PERSON_ID + "|" + LEGISLATION_CODE + "|" + HIGHEST_EDUCATION_LEVEL + "|"
				+ MARITAL_STATUS + "|" + MARITAL_STATUS_DATE + "|" + SEX + "|" + ATTRIBUTE_CATEGORY + "|" + ATTRIBUTE1
				+ "|" + ATTRIBUTE2 + "|" + ATTRIBUTE3 + "|" + ATTRIBUTE4 + "|" + ATTRIBUTE5 + "|" + ATTRIBUTE6 + "|"
				+ ATTRIBUTE7 + "|" + ATTRIBUTE8 + "|" + ATTRIBUTE9 + "|" + ATTRIBUTE10 + "|" + ATTRIBUTE11 + "|"
				+ ATTRIBUTE12 + "|" + ATTRIBUTE13 + "|" + ATTRIBUTE14 + "|" + ATTRIBUTE15 + "|" + ATTRIBUTE16 + "|"
				+ ATTRIBUTE17 + "|" + ATTRIBUTE18 + "|" + ATTRIBUTE19 + "|" + ATTRIBUTE20 + "|" + ATTRIBUTE21 + "|"
				+ ATTRIBUTE22 + "|" + ATTRIBUTE23 + "|" + ATTRIBUTE24 + "|" + ATTRIBUTE25 + "|" + ATTRIBUTE26 + "|"
				+ ATTRIBUTE27 + "|" + ATTRIBUTE28 + "|" + ATTRIBUTE29 + "|" + ATTRIBUTE30 + "|"
				+ PER_INFROMATION_CATEGORY + "|" + PER_INFORMATION1 + "|" + PER_INFORMATION2 + "|" + PER_INFORMATION3
				+ "|" + PER_INFORMATION4 + "|" + PER_INFORMATION5 + "|" + PER_INFORMATION6 + "|" + PER_INFORMATION7
				+ "|" + PER_INFORMATION8 + "|" + PER_INFORMATION9 + "|" + PER_INFORMATION10 + "|" + PER_INFORMATION11
				+ "|" + PER_INFORMATION12 + "|" + PER_INFORMATION13 + "|" + PER_INFORMATION14 + "|" + PER_INFORMATION15
				+ "|" + PER_INFORMATION16 + "|" + PER_INFORMATION17 + "|" + PER_INFORMATION18 + "|" + PER_INFORMATION19
				+ "|" + PER_INFORMATION20 + "|" + PER_INFORMATION21 + "|" + PER_INFORMATION22 + "|" + PER_INFORMATION23
				+ "|" + PER_INFORMATION24 + "|" + PER_INFORMATION25 + "|" + PER_INFORMATION26 + "|" + PER_INFORMATION27
				+ "|" + PER_INFORMATION28 + "|" + PER_INFORMATION29 + "|" + PER_INFORMATION30 + "|"
				+ PER_INFORMATION_DATE1 + "|" + PER_INFORMATION_DATE2 + "|" + PER_INFORMATION_DATE3 + "|"
				+ PER_INFORMATION_DATE4 + "|" + PER_INFORMATION_DATE5 + "|" + PER_INFORMATION_DATE6 + "|"
				+ PER_INFORMATION_DATE7 + "|" + PER_INFORMATION_DATE8 + "|" + PER_INFORMATION_DATE9 + "|"
				+ PER_INFORMATION_DATE10 + "|" + PER_INFORMATION_DATE11 + "|" + PER_INFORMATION_DATE12 + "|"
				+ PER_INFORMATION_DATE13 + "|" + PER_INFORMATION_DATE14 + "|" + PER_INFORMATION_DATE15 + "|"
				+ PER_INFORMATION_NUMBER1 + "|" + PER_INFORMATION_NUMBER2 + "|" + PER_INFORMATION_NUMBER3 + "|"
				+ PER_INFORMATION_NUMBER4 + "|" + PER_INFORMATION_NUMBER5 + "|" + PER_INFORMATION_NUMBER6 + "|"
				+ PER_INFORMATION_NUMBER7 + "|" + PER_INFORMATION_NUMBER8 + "|" + PER_INFORMATION_NUMBER9 + "|"
				+ PER_INFORMATION_NUMBER10 + "|" + PER_INFORMATION_NUMBER11 + "|" + PER_INFORMATION_NUMBER12 + "|"
				+ PER_INFORMATION_NUMBER13 + "|" + PER_INFORMATION_NUMBER14 + "|" + PER_INFORMATION_NUMBER15 + "|"
				+ PER_INFORMATION_NUMBER16 + "|" + PER_INFORMATION_NUMBER17 + "|" + PER_INFORMATION_NUMBER18 + "|"
				+ PER_INFORMATION_NUMBER19 + "|" + PER_INFORMATION_NUMBER20 + "|" + FT_ALTERNATE_REC + "|"
				+ FT_ALTERNATE_KEY;
	}



	public String getPERSON_LEGISLATIVE_ID() {
		return PERSON_LEGISLATIVE_ID;
	}

	public void setPERSON_LEGISLATIVE_ID(String pERSON_LEGISLATIVE_ID) {
		PERSON_LEGISLATIVE_ID = pERSON_LEGISLATIVE_ID;
	}

	public String getEFFECTIVE_START_DATE() {
		return EFFECTIVE_START_DATE;
	}

	public void setEFFECTIVE_START_DATE(String eFFECTIVE_START_DATE) {
		EFFECTIVE_START_DATE = eFFECTIVE_START_DATE;
	}

	public String getEFFECTIVE_END_DATE() {
		return EFFECTIVE_END_DATE;
	}

	public void setEFFECTIVE_END_DATE(String eFFECTIVE_END_DATE) {
		EFFECTIVE_END_DATE = eFFECTIVE_END_DATE;
	}

	public String getBUSINESS_GROUP_ID() {
		return BUSINESS_GROUP_ID;
	}

	public void setBUSINESS_GROUP_ID(String bUSINESS_GROUP_ID) {
		BUSINESS_GROUP_ID = bUSINESS_GROUP_ID;
	}

	public String getPERSON_ID() {
		return PERSON_ID;
	}

	public void setPERSON_ID(String pERSON_ID) {
		PERSON_ID = pERSON_ID;
	}

	public String getLEGISLATION_CODE() {
		return LEGISLATION_CODE;
	}

	public void setLEGISLATION_CODE(String lEGISLATION_CODE) {
		LEGISLATION_CODE = lEGISLATION_CODE;
	}

	public String getHIGHEST_EDUCATION_LEVEL() {
		return HIGHEST_EDUCATION_LEVEL;
	}

	public void setHIGHEST_EDUCATION_LEVEL(String hIGHEST_EDUCATION_LEVEL) {
		HIGHEST_EDUCATION_LEVEL = hIGHEST_EDUCATION_LEVEL;
	}

	public String getMARITAL_STATUS() {
		return MARITAL_STATUS;
	}

	public void setMARITAL_STATUS(String mARITAL_STATUS) {
		MARITAL_STATUS = mARITAL_STATUS;
	}

	public String getMARITAL_STATUS_DATE() {
		return MARITAL_STATUS_DATE;
	}

	public void setMARITAL_STATUS_DATE(String mARITAL_STATUS_DATE) {
		MARITAL_STATUS_DATE = mARITAL_STATUS_DATE;
	}

	public String getSEX() {
		return SEX;
	}

	public void setSEX(String sEX) {
		SEX = sEX;
	}



	public String getATTRIBUTE_CATEGORY() {
		return ATTRIBUTE_CATEGORY;
	}



	public void setATTRIBUTE_CATEGORY(String aTTRIBUTE_CATEGORY) {
		ATTRIBUTE_CATEGORY = aTTRIBUTE_CATEGORY;
	}



	public String getATTRIBUTE1() {
		return ATTRIBUTE1;
	}



	public void setATTRIBUTE1(String aTTRIBUTE1) {
		ATTRIBUTE1 = aTTRIBUTE1;
	}



	public String getATTRIBUTE2() {
		return ATTRIBUTE2;
	}



	public void setATTRIBUTE2(String aTTRIBUTE2) {
		ATTRIBUTE2 = aTTRIBUTE2;
	}



	public String getATTRIBUTE3() {
		return ATTRIBUTE3;
	}



	public void setATTRIBUTE3(String aTTRIBUTE3) {
		ATTRIBUTE3 = aTTRIBUTE3;
	}



	public String getATTRIBUTE4() {
		return ATTRIBUTE4;
	}



	public void setATTRIBUTE4(String aTTRIBUTE4) {
		ATTRIBUTE4 = aTTRIBUTE4;
	}



	public String getATTRIBUTE5() {
		return ATTRIBUTE5;
	}



	public void setATTRIBUTE5(String aTTRIBUTE5) {
		ATTRIBUTE5 = aTTRIBUTE5;
	}



	public String getATTRIBUTE6() {
		return ATTRIBUTE6;
	}



	public void setATTRIBUTE6(String aTTRIBUTE6) {
		ATTRIBUTE6 = aTTRIBUTE6;
	}



	public String getATTRIBUTE7() {
		return ATTRIBUTE7;
	}



	public void setATTRIBUTE7(String aTTRIBUTE7) {
		ATTRIBUTE7 = aTTRIBUTE7;
	}



	public String getATTRIBUTE8() {
		return ATTRIBUTE8;
	}



	public void setATTRIBUTE8(String aTTRIBUTE8) {
		ATTRIBUTE8 = aTTRIBUTE8;
	}



	public String getATTRIBUTE9() {
		return ATTRIBUTE9;
	}



	public void setATTRIBUTE9(String aTTRIBUTE9) {
		ATTRIBUTE9 = aTTRIBUTE9;
	}



	public String getATTRIBUTE10() {
		return ATTRIBUTE10;
	}



	public void setATTRIBUTE10(String aTTRIBUTE10) {
		ATTRIBUTE10 = aTTRIBUTE10;
	}



	public String getATTRIBUTE11() {
		return ATTRIBUTE11;
	}



	public void setATTRIBUTE11(String aTTRIBUTE11) {
		ATTRIBUTE11 = aTTRIBUTE11;
	}



	public String getATTRIBUTE12() {
		return ATTRIBUTE12;
	}



	public void setATTRIBUTE12(String aTTRIBUTE12) {
		ATTRIBUTE12 = aTTRIBUTE12;
	}



	public String getATTRIBUTE13() {
		return ATTRIBUTE13;
	}



	public void setATTRIBUTE13(String aTTRIBUTE13) {
		ATTRIBUTE13 = aTTRIBUTE13;
	}



	public String getATTRIBUTE14() {
		return ATTRIBUTE14;
	}



	public void setATTRIBUTE14(String aTTRIBUTE14) {
		ATTRIBUTE14 = aTTRIBUTE14;
	}



	public String getATTRIBUTE15() {
		return ATTRIBUTE15;
	}



	public void setATTRIBUTE15(String aTTRIBUTE15) {
		ATTRIBUTE15 = aTTRIBUTE15;
	}



	public String getATTRIBUTE16() {
		return ATTRIBUTE16;
	}



	public void setATTRIBUTE16(String aTTRIBUTE16) {
		ATTRIBUTE16 = aTTRIBUTE16;
	}



	public String getATTRIBUTE17() {
		return ATTRIBUTE17;
	}



	public void setATTRIBUTE17(String aTTRIBUTE17) {
		ATTRIBUTE17 = aTTRIBUTE17;
	}



	public String getATTRIBUTE18() {
		return ATTRIBUTE18;
	}



	public void setATTRIBUTE18(String aTTRIBUTE18) {
		ATTRIBUTE18 = aTTRIBUTE18;
	}



	public String getATTRIBUTE19() {
		return ATTRIBUTE19;
	}



	public void setATTRIBUTE19(String aTTRIBUTE19) {
		ATTRIBUTE19 = aTTRIBUTE19;
	}



	public String getATTRIBUTE20() {
		return ATTRIBUTE20;
	}



	public void setATTRIBUTE20(String aTTRIBUTE20) {
		ATTRIBUTE20 = aTTRIBUTE20;
	}



	public String getATTRIBUTE21() {
		return ATTRIBUTE21;
	}



	public void setATTRIBUTE21(String aTTRIBUTE21) {
		ATTRIBUTE21 = aTTRIBUTE21;
	}



	public String getATTRIBUTE22() {
		return ATTRIBUTE22;
	}



	public void setATTRIBUTE22(String aTTRIBUTE22) {
		ATTRIBUTE22 = aTTRIBUTE22;
	}



	public String getATTRIBUTE23() {
		return ATTRIBUTE23;
	}



	public void setATTRIBUTE23(String aTTRIBUTE23) {
		ATTRIBUTE23 = aTTRIBUTE23;
	}



	public String getATTRIBUTE24() {
		return ATTRIBUTE24;
	}



	public void setATTRIBUTE24(String aTTRIBUTE24) {
		ATTRIBUTE24 = aTTRIBUTE24;
	}



	public String getATTRIBUTE25() {
		return ATTRIBUTE25;
	}



	public void setATTRIBUTE25(String aTTRIBUTE25) {
		ATTRIBUTE25 = aTTRIBUTE25;
	}



	public String getATTRIBUTE26() {
		return ATTRIBUTE26;
	}



	public void setATTRIBUTE26(String aTTRIBUTE26) {
		ATTRIBUTE26 = aTTRIBUTE26;
	}



	public String getATTRIBUTE27() {
		return ATTRIBUTE27;
	}



	public void setATTRIBUTE27(String aTTRIBUTE27) {
		ATTRIBUTE27 = aTTRIBUTE27;
	}



	public String getATTRIBUTE28() {
		return ATTRIBUTE28;
	}



	public void setATTRIBUTE28(String aTTRIBUTE28) {
		ATTRIBUTE28 = aTTRIBUTE28;
	}



	public String getATTRIBUTE29() {
		return ATTRIBUTE29;
	}



	public void setATTRIBUTE29(String aTTRIBUTE29) {
		ATTRIBUTE29 = aTTRIBUTE29;
	}



	public String getATTRIBUTE30() {
		return ATTRIBUTE30;
	}



	public void setATTRIBUTE30(String aTTRIBUTE30) {
		ATTRIBUTE30 = aTTRIBUTE30;
	}



	public String getPER_INFROMATION_CATEGORY() {
		return PER_INFROMATION_CATEGORY;
	}



	public void setPER_INFROMATION_CATEGORY(String pER_INFROMATION_CATEGORY) {
		PER_INFROMATION_CATEGORY = pER_INFROMATION_CATEGORY;
	}



	public String getPER_INFORMATION1() {
		return PER_INFORMATION1;
	}



	public void setPER_INFORMATION1(String pER_INFORMATION1) {
		PER_INFORMATION1 = pER_INFORMATION1;
	}



	public String getPER_INFORMATION2() {
		return PER_INFORMATION2;
	}



	public void setPER_INFORMATION2(String pER_INFORMATION2) {
		PER_INFORMATION2 = pER_INFORMATION2;
	}



	public String getPER_INFORMATION3() {
		return PER_INFORMATION3;
	}



	public void setPER_INFORMATION3(String pER_INFORMATION3) {
		PER_INFORMATION3 = pER_INFORMATION3;
	}



	public String getPER_INFORMATION4() {
		return PER_INFORMATION4;
	}



	public void setPER_INFORMATION4(String pER_INFORMATION4) {
		PER_INFORMATION4 = pER_INFORMATION4;
	}



	public String getPER_INFORMATION5() {
		return PER_INFORMATION5;
	}



	public void setPER_INFORMATION5(String pER_INFORMATION5) {
		PER_INFORMATION5 = pER_INFORMATION5;
	}



	public String getPER_INFORMATION6() {
		return PER_INFORMATION6;
	}



	public void setPER_INFORMATION6(String pER_INFORMATION6) {
		PER_INFORMATION6 = pER_INFORMATION6;
	}



	public String getPER_INFORMATION7() {
		return PER_INFORMATION7;
	}



	public void setPER_INFORMATION7(String pER_INFORMATION7) {
		PER_INFORMATION7 = pER_INFORMATION7;
	}



	public String getPER_INFORMATION8() {
		return PER_INFORMATION8;
	}



	public void setPER_INFORMATION8(String pER_INFORMATION8) {
		PER_INFORMATION8 = pER_INFORMATION8;
	}



	public String getPER_INFORMATION9() {
		return PER_INFORMATION9;
	}



	public void setPER_INFORMATION9(String pER_INFORMATION9) {
		PER_INFORMATION9 = pER_INFORMATION9;
	}



	public String getPER_INFORMATION10() {
		return PER_INFORMATION10;
	}



	public void setPER_INFORMATION10(String pER_INFORMATION10) {
		PER_INFORMATION10 = pER_INFORMATION10;
	}



	public String getPER_INFORMATION11() {
		return PER_INFORMATION11;
	}



	public void setPER_INFORMATION11(String pER_INFORMATION11) {
		PER_INFORMATION11 = pER_INFORMATION11;
	}



	public String getPER_INFORMATION12() {
		return PER_INFORMATION12;
	}



	public void setPER_INFORMATION12(String pER_INFORMATION12) {
		PER_INFORMATION12 = pER_INFORMATION12;
	}



	public String getPER_INFORMATION13() {
		return PER_INFORMATION13;
	}



	public void setPER_INFORMATION13(String pER_INFORMATION13) {
		PER_INFORMATION13 = pER_INFORMATION13;
	}



	public String getPER_INFORMATION14() {
		return PER_INFORMATION14;
	}



	public void setPER_INFORMATION14(String pER_INFORMATION14) {
		PER_INFORMATION14 = pER_INFORMATION14;
	}



	public String getPER_INFORMATION15() {
		return PER_INFORMATION15;
	}



	public void setPER_INFORMATION15(String pER_INFORMATION15) {
		PER_INFORMATION15 = pER_INFORMATION15;
	}



	public String getPER_INFORMATION16() {
		return PER_INFORMATION16;
	}



	public void setPER_INFORMATION16(String pER_INFORMATION16) {
		PER_INFORMATION16 = pER_INFORMATION16;
	}



	public String getPER_INFORMATION17() {
		return PER_INFORMATION17;
	}



	public void setPER_INFORMATION17(String pER_INFORMATION17) {
		PER_INFORMATION17 = pER_INFORMATION17;
	}



	public String getPER_INFORMATION18() {
		return PER_INFORMATION18;
	}



	public void setPER_INFORMATION18(String pER_INFORMATION18) {
		PER_INFORMATION18 = pER_INFORMATION18;
	}



	public String getPER_INFORMATION19() {
		return PER_INFORMATION19;
	}



	public void setPER_INFORMATION19(String pER_INFORMATION19) {
		PER_INFORMATION19 = pER_INFORMATION19;
	}



	public String getPER_INFORMATION20() {
		return PER_INFORMATION20;
	}



	public void setPER_INFORMATION20(String pER_INFORMATION20) {
		PER_INFORMATION20 = pER_INFORMATION20;
	}



	public String getPER_INFORMATION21() {
		return PER_INFORMATION21;
	}



	public void setPER_INFORMATION21(String pER_INFORMATION21) {
		PER_INFORMATION21 = pER_INFORMATION21;
	}



	public String getPER_INFORMATION22() {
		return PER_INFORMATION22;
	}



	public void setPER_INFORMATION22(String pER_INFORMATION22) {
		PER_INFORMATION22 = pER_INFORMATION22;
	}



	public String getPER_INFORMATION23() {
		return PER_INFORMATION23;
	}



	public void setPER_INFORMATION23(String pER_INFORMATION23) {
		PER_INFORMATION23 = pER_INFORMATION23;
	}



	public String getPER_INFORMATION24() {
		return PER_INFORMATION24;
	}



	public void setPER_INFORMATION24(String pER_INFORMATION24) {
		PER_INFORMATION24 = pER_INFORMATION24;
	}



	public String getPER_INFORMATION25() {
		return PER_INFORMATION25;
	}



	public void setPER_INFORMATION25(String pER_INFORMATION25) {
		PER_INFORMATION25 = pER_INFORMATION25;
	}



	public String getPER_INFORMATION26() {
		return PER_INFORMATION26;
	}



	public void setPER_INFORMATION26(String pER_INFORMATION26) {
		PER_INFORMATION26 = pER_INFORMATION26;
	}



	public String getPER_INFORMATION27() {
		return PER_INFORMATION27;
	}



	public void setPER_INFORMATION27(String pER_INFORMATION27) {
		PER_INFORMATION27 = pER_INFORMATION27;
	}



	public String getPER_INFORMATION28() {
		return PER_INFORMATION28;
	}



	public void setPER_INFORMATION28(String pER_INFORMATION28) {
		PER_INFORMATION28 = pER_INFORMATION28;
	}



	public String getPER_INFORMATION29() {
		return PER_INFORMATION29;
	}



	public void setPER_INFORMATION29(String pER_INFORMATION29) {
		PER_INFORMATION29 = pER_INFORMATION29;
	}



	public String getPER_INFORMATION30() {
		return PER_INFORMATION30;
	}



	public void setPER_INFORMATION30(String pER_INFORMATION30) {
		PER_INFORMATION30 = pER_INFORMATION30;
	}



	public String getPER_INFORMATION_DATE1() {
		return PER_INFORMATION_DATE1;
	}



	public void setPER_INFORMATION_DATE1(String pER_INFORMATION_DATE1) {
		PER_INFORMATION_DATE1 = pER_INFORMATION_DATE1;
	}



	public String getPER_INFORMATION_DATE2() {
		return PER_INFORMATION_DATE2;
	}



	public void setPER_INFORMATION_DATE2(String pER_INFORMATION_DATE2) {
		PER_INFORMATION_DATE2 = pER_INFORMATION_DATE2;
	}



	public String getPER_INFORMATION_DATE3() {
		return PER_INFORMATION_DATE3;
	}



	public void setPER_INFORMATION_DATE3(String pER_INFORMATION_DATE3) {
		PER_INFORMATION_DATE3 = pER_INFORMATION_DATE3;
	}



	public String getPER_INFORMATION_DATE4() {
		return PER_INFORMATION_DATE4;
	}



	public void setPER_INFORMATION_DATE4(String pER_INFORMATION_DATE4) {
		PER_INFORMATION_DATE4 = pER_INFORMATION_DATE4;
	}



	public String getPER_INFORMATION_DATE5() {
		return PER_INFORMATION_DATE5;
	}



	public void setPER_INFORMATION_DATE5(String pER_INFORMATION_DATE5) {
		PER_INFORMATION_DATE5 = pER_INFORMATION_DATE5;
	}



	public String getPER_INFORMATION_DATE6() {
		return PER_INFORMATION_DATE6;
	}



	public void setPER_INFORMATION_DATE6(String pER_INFORMATION_DATE6) {
		PER_INFORMATION_DATE6 = pER_INFORMATION_DATE6;
	}



	public String getPER_INFORMATION_DATE7() {
		return PER_INFORMATION_DATE7;
	}



	public void setPER_INFORMATION_DATE7(String pER_INFORMATION_DATE7) {
		PER_INFORMATION_DATE7 = pER_INFORMATION_DATE7;
	}



	public String getPER_INFORMATION_DATE8() {
		return PER_INFORMATION_DATE8;
	}



	public void setPER_INFORMATION_DATE8(String pER_INFORMATION_DATE8) {
		PER_INFORMATION_DATE8 = pER_INFORMATION_DATE8;
	}



	public String getPER_INFORMATION_DATE9() {
		return PER_INFORMATION_DATE9;
	}



	public void setPER_INFORMATION_DATE9(String pER_INFORMATION_DATE9) {
		PER_INFORMATION_DATE9 = pER_INFORMATION_DATE9;
	}



	public String getPER_INFORMATION_DATE10() {
		return PER_INFORMATION_DATE10;
	}



	public void setPER_INFORMATION_DATE10(String pER_INFORMATION_DATE10) {
		PER_INFORMATION_DATE10 = pER_INFORMATION_DATE10;
	}



	public String getPER_INFORMATION_DATE11() {
		return PER_INFORMATION_DATE11;
	}



	public void setPER_INFORMATION_DATE11(String pER_INFORMATION_DATE11) {
		PER_INFORMATION_DATE11 = pER_INFORMATION_DATE11;
	}



	public String getPER_INFORMATION_DATE12() {
		return PER_INFORMATION_DATE12;
	}



	public void setPER_INFORMATION_DATE12(String pER_INFORMATION_DATE12) {
		PER_INFORMATION_DATE12 = pER_INFORMATION_DATE12;
	}



	public String getPER_INFORMATION_DATE13() {
		return PER_INFORMATION_DATE13;
	}



	public void setPER_INFORMATION_DATE13(String pER_INFORMATION_DATE13) {
		PER_INFORMATION_DATE13 = pER_INFORMATION_DATE13;
	}



	public String getPER_INFORMATION_DATE14() {
		return PER_INFORMATION_DATE14;
	}



	public void setPER_INFORMATION_DATE14(String pER_INFORMATION_DATE14) {
		PER_INFORMATION_DATE14 = pER_INFORMATION_DATE14;
	}



	public String getPER_INFORMATION_DATE15() {
		return PER_INFORMATION_DATE15;
	}



	public void setPER_INFORMATION_DATE15(String pER_INFORMATION_DATE15) {
		PER_INFORMATION_DATE15 = pER_INFORMATION_DATE15;
	}



	public String getPER_INFORMATION_NUMBER1() {
		return PER_INFORMATION_NUMBER1;
	}



	public void setPER_INFORMATION_NUMBER1(String pER_INFORMATION_NUMBER1) {
		PER_INFORMATION_NUMBER1 = pER_INFORMATION_NUMBER1;
	}



	public String getPER_INFORMATION_NUMBER2() {
		return PER_INFORMATION_NUMBER2;
	}



	public void setPER_INFORMATION_NUMBER2(String pER_INFORMATION_NUMBER2) {
		PER_INFORMATION_NUMBER2 = pER_INFORMATION_NUMBER2;
	}



	public String getPER_INFORMATION_NUMBER3() {
		return PER_INFORMATION_NUMBER3;
	}



	public void setPER_INFORMATION_NUMBER3(String pER_INFORMATION_NUMBER3) {
		PER_INFORMATION_NUMBER3 = pER_INFORMATION_NUMBER3;
	}



	public String getPER_INFORMATION_NUMBER4() {
		return PER_INFORMATION_NUMBER4;
	}



	public void setPER_INFORMATION_NUMBER4(String pER_INFORMATION_NUMBER4) {
		PER_INFORMATION_NUMBER4 = pER_INFORMATION_NUMBER4;
	}



	public String getPER_INFORMATION_NUMBER5() {
		return PER_INFORMATION_NUMBER5;
	}



	public void setPER_INFORMATION_NUMBER5(String pER_INFORMATION_NUMBER5) {
		PER_INFORMATION_NUMBER5 = pER_INFORMATION_NUMBER5;
	}



	public String getPER_INFORMATION_NUMBER6() {
		return PER_INFORMATION_NUMBER6;
	}



	public void setPER_INFORMATION_NUMBER6(String pER_INFORMATION_NUMBER6) {
		PER_INFORMATION_NUMBER6 = pER_INFORMATION_NUMBER6;
	}



	public String getPER_INFORMATION_NUMBER7() {
		return PER_INFORMATION_NUMBER7;
	}



	public void setPER_INFORMATION_NUMBER7(String pER_INFORMATION_NUMBER7) {
		PER_INFORMATION_NUMBER7 = pER_INFORMATION_NUMBER7;
	}



	public String getPER_INFORMATION_NUMBER8() {
		return PER_INFORMATION_NUMBER8;
	}



	public void setPER_INFORMATION_NUMBER8(String pER_INFORMATION_NUMBER8) {
		PER_INFORMATION_NUMBER8 = pER_INFORMATION_NUMBER8;
	}



	public String getPER_INFORMATION_NUMBER9() {
		return PER_INFORMATION_NUMBER9;
	}



	public void setPER_INFORMATION_NUMBER9(String pER_INFORMATION_NUMBER9) {
		PER_INFORMATION_NUMBER9 = pER_INFORMATION_NUMBER9;
	}



	public String getPER_INFORMATION_NUMBER10() {
		return PER_INFORMATION_NUMBER10;
	}



	public void setPER_INFORMATION_NUMBER10(String pER_INFORMATION_NUMBER10) {
		PER_INFORMATION_NUMBER10 = pER_INFORMATION_NUMBER10;
	}



	public String getPER_INFORMATION_NUMBER11() {
		return PER_INFORMATION_NUMBER11;
	}



	public void setPER_INFORMATION_NUMBER11(String pER_INFORMATION_NUMBER11) {
		PER_INFORMATION_NUMBER11 = pER_INFORMATION_NUMBER11;
	}



	public String getPER_INFORMATION_NUMBER12() {
		return PER_INFORMATION_NUMBER12;
	}



	public void setPER_INFORMATION_NUMBER12(String pER_INFORMATION_NUMBER12) {
		PER_INFORMATION_NUMBER12 = pER_INFORMATION_NUMBER12;
	}



	public String getPER_INFORMATION_NUMBER13() {
		return PER_INFORMATION_NUMBER13;
	}



	public void setPER_INFORMATION_NUMBER13(String pER_INFORMATION_NUMBER13) {
		PER_INFORMATION_NUMBER13 = pER_INFORMATION_NUMBER13;
	}



	public String getPER_INFORMATION_NUMBER14() {
		return PER_INFORMATION_NUMBER14;
	}



	public void setPER_INFORMATION_NUMBER14(String pER_INFORMATION_NUMBER14) {
		PER_INFORMATION_NUMBER14 = pER_INFORMATION_NUMBER14;
	}



	public String getPER_INFORMATION_NUMBER15() {
		return PER_INFORMATION_NUMBER15;
	}



	public void setPER_INFORMATION_NUMBER15(String pER_INFORMATION_NUMBER15) {
		PER_INFORMATION_NUMBER15 = pER_INFORMATION_NUMBER15;
	}



	public String getPER_INFORMATION_NUMBER16() {
		return PER_INFORMATION_NUMBER16;
	}



	public void setPER_INFORMATION_NUMBER16(String pER_INFORMATION_NUMBER16) {
		PER_INFORMATION_NUMBER16 = pER_INFORMATION_NUMBER16;
	}



	public String getPER_INFORMATION_NUMBER17() {
		return PER_INFORMATION_NUMBER17;
	}



	public void setPER_INFORMATION_NUMBER17(String pER_INFORMATION_NUMBER17) {
		PER_INFORMATION_NUMBER17 = pER_INFORMATION_NUMBER17;
	}



	public String getPER_INFORMATION_NUMBER18() {
		return PER_INFORMATION_NUMBER18;
	}



	public void setPER_INFORMATION_NUMBER18(String pER_INFORMATION_NUMBER18) {
		PER_INFORMATION_NUMBER18 = pER_INFORMATION_NUMBER18;
	}



	public String getPER_INFORMATION_NUMBER19() {
		return PER_INFORMATION_NUMBER19;
	}



	public void setPER_INFORMATION_NUMBER19(String pER_INFORMATION_NUMBER19) {
		PER_INFORMATION_NUMBER19 = pER_INFORMATION_NUMBER19;
	}



	public String getPER_INFORMATION_NUMBER20() {
		return PER_INFORMATION_NUMBER20;
	}



	public void setPER_INFORMATION_NUMBER20(String pER_INFORMATION_NUMBER20) {
		PER_INFORMATION_NUMBER20 = pER_INFORMATION_NUMBER20;
	}



	public String getFT_ALTERNATE_REC() {
		return FT_ALTERNATE_REC;
	}



	public void setFT_ALTERNATE_REC(String fT_ALTERNATE_REC) {
		FT_ALTERNATE_REC = fT_ALTERNATE_REC;
	}



	public String getFT_ALTERNATE_KEY() {
		return FT_ALTERNATE_KEY;
	}



	public void setFT_ALTERNATE_KEY(String fT_ALTERNATE_KEY) {
		FT_ALTERNATE_KEY = fT_ALTERNATE_KEY;
	}


}
