CREATE TABLE "APPS"."XXINV_INTEGRATION_PERSON" 
   (	"PERSON_ID" VARCHAR2(30 BYTE), 
	"PERSON_NUMBER" VARCHAR2(100 BYTE), 
	"EMPLOYEE_CODE" VARCHAR2(100 BYTE), 
	"TALEO_EMP_ID" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
  
 CREATE TABLE "APPS"."XXINV_INTEGRATION_HCM_MAP" 
   (	"HCMGUID" VARCHAR2(100 BYTE), 
	"HCMKEY" VARCHAR2(300 BYTE), 
	"SRC_DATA" VARCHAR2(300 BYTE), 
	"DESCRIPTION" VARCHAR2(300 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE TABLE "APPS"."XXINV_INTEGRATION_INTERFACE" 
   (	"INTERFACE_ID" VARCHAR2(100 BYTE), 
	"UPDATE_DATE" VARCHAR2(300 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

    CREATE TABLE APPS.XXINV_INSERT_PERID_TEMP 
   (	WORK_EMAIL VARCHAR2(100 BYTE), 
	PERSON_ID VARCHAR2(100 BYTE), 
	FBL_PER_ID VARCHAR2(100 BYTE), 
	PERSON_NUM VARCHAR2(100 BYTE)
   ) ;
  --------------------------------------------------------
--  DDL for Table XXINV_INTEGRATION_HCM_MAP
--------------------------------------------------------

  CREATE TABLE "APPS"."XXINV_INTEGRATION_HCM_MAP" 
   (	"HCMGUID" VARCHAR2(100 BYTE), 
	"HCMKEY" VARCHAR2(300 BYTE), 
	"SRC_DATA" VARCHAR2(300 BYTE), 
	"DESCRIPTION" VARCHAR2(300 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
REM INSERTING into APPS.XXINV_INTEGRATION_HCM_MAP
SET DEFINE OFF;
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Manitoba','CA-MB','CA-MB');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'New Brunswick','CA-NB','CA-NB');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Newfoundland and Labrador','CA-NL','CA-NL');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Nova Scotia','CA-NS','CA-NS');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Ontario','CA-ON','CA-ON');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Prince Edward Island','CA-PE','CA-PE');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Quebec','CA-QC','CA-QC');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Saskatchewan','CA-SK','CA-SK');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Northwest Territories','CA-NT','CA-NT');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Nunavut','CA-NU','CA-NU');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Yukon','CA-YT','CA-YT');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Shanghai','CN-31','CN-31');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Alberta','CA-AB','CA-AB');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Beijing','CN-11','CN-11');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Asia - Taiwan','CN-71','CN-71');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values ('16D10864505D1808E0532E90C10A549D','300000002772029','InvenSense GK (Japan)','US');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values ('16D1086450661808E0532E90C10A549D','300000002773037','AE Legislative Data Group','AE');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values ('16D10864505C1808E0532E90C10A549D','300000002772012','InvenSense US (HQ)','US');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values ('16D10864505E1808E0532E90C10A549D','300000002772061','InvenSense Int''l FZE (Dubai)','US');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values ('16D10864505F1808E0532E90C10A549D','300000002772093','InvenSense Korea','US');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values ('16D1086450601808E0532E90C10A549D','300000002772125','InvenSense Canada','US');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values ('16D1086450611808E0532E90C10A549D','300000002772157','InvenSense Slovakia S.R.O.','US');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values ('16D1086450621808E0532E90C10A549D','300000002773059','Invensense Taiwan Co., Ltd.','US');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values ('16D1086450631808E0532E90C10A549D','300000002773106','InvenSense China Ltd','US');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values ('16D1086450641808E0532E90C10A549D','300000002773123','InvenSense France','US');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values ('16D1086450651808E0532E90C10A549D','300000002773155','InvenSense Italy','US');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values ('170F9C911EC28FCAE0532D90C10AEDD5','300000002772482','Invensense Taiwan Sales Co., Ltd','US');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values ('16D1086450671808E0532E90C10A549D','300000002773041','CA Legislative Data Group','CA');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values ('16D1086450681808E0532E90C10A549D','300000002773038','CN Legislative Data Group','CN');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values ('16D1086450691808E0532E90C10A549D','300000002773042','FR Legislative Data Group','FR');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values ('16D10864506A1808E0532E90C10A549D','300000002773043','IT Legislative Data Group','IT');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values ('16D10864506B1808E0532E90C10A549D','300000002773036','JP Legislative Data Group','JP');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values ('16D10864506C1808E0532E90C10A549D','300000002773039','KR Legislative Data Group','KR');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values ('16D10864506D1808E0532E90C10A549D','300000002773040','SK Legislative Data Group','SK');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values ('16D10864506E1808E0532E90C10A549D','300000002773035','TW Legislative Data Group','TW');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values ('16D10864506F1808E0532E90C10A549D','300000002773034','US Legislative Data Group','US');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'100000000385585','Advanced Technology','Advanced Technology');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'100000000430123','Corporate Development','Corporate Development');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'100000000385586','Engineering, Motion Product Development','Engineering, Motion Product Development');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'100000000385587','Executive Management','Executive Management');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'100000000385588','Finance','Finance');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'100000000385589','Human Resources','Human Resources');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'100000000385590','IT/Facilities','IT/Facilities');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'100000000385591','Legal','Legal');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'100000000385592','Marketing and Business Development','Marketing and Business Development');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'100000000385593','Operations','Operations');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'100000000385594','Sales','Sales');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'100000000385595','Software Engineering','Software Engineering');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Alabama','AL','AL');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Alaska','AK','AK');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Arizona','AZ','AZ');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Arkansas','AR','AR');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'California','CA','CA');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Colorado','CO','CO');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Connecticut','CT','CT');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Delaware','DE','DE');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Florida','FL','FL');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Georgia','GA','GA');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Hawaii','HI','HI');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Idaho','ID','ID');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Illinois','IL','IL');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Indiana','IN','IN');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Iowa','IA','IA');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Kansas','KS','KS');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Kentucky','KY','KY');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Louisiana','LA','LA');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Maine','ME','ME');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Maryland','MD','MD');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Massachusetts','MA','MA');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Michigan','MI','MI');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Minnesota','MN','MN');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Mississippi','MS','MS');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Missouri','MO','MO');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Montana','MT','MT');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Nebraska','NE','NE');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Nevada','NV','NV');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'New Hampshire','NH','NH');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'New Jersey','NJ','NJ');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'New Mexico','NM','NM');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'New York','NY','NY');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'North Carolina','NC','NC');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'North Dakota','ND','ND');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Ohio','OH','OH');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Oklahoma','OK','OK');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Oregon','OR','OR');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Pennsylvania','PA','PA');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Rhode Island','RI','RI');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'South Carolina','SC','SC');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'South Dakota','SD','SD');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Texas','TX','TX');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Utah','UT','UT');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Vermont','VT','VT');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Virginia','VA','VA');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Washington','WA','WA');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'West Virginia','WV','WV');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Wisconsin','WI','WI');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Wyoming','WY','WY');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'District of Columbia','DC','DC');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'American Samoa','AS','AS');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Guam','GU','GU');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Northern Mariana Islands','MP','MP');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Puerto Rico','PR','PR');
Insert into APPS.XXINV_INTEGRATION_HCM_MAP (HCMGUID,HCMKEY,SRC_DATA,DESCRIPTION) values (null,'Virgin Islands','VI','VI');

--------------------------------------------------------
--  DDL for Table XXINV_INTEGRATION_INTERFACE
--------------------------------------------------------

  CREATE TABLE "APPS"."XXINV_INTEGRATION_INTERFACE" 
   (	"INTERFACE_ID" VARCHAR2(100 BYTE), 
	"UPDATE_DATE" VARCHAR2(300 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
REM INSERTING into APPS.XXINV_INTEGRATION_INTERFACE
SET DEFINE OFF;
Insert into APPS.XXINV_INTEGRATION_INTERFACE (INTERFACE_ID,UPDATE_DATE) values ('createEmployee','2017-02-02T04:00PST');
Insert into APPS.XXINV_INTEGRATION_INTERFACE (INTERFACE_ID,UPDATE_DATE) values ('createTaleoLocation','2016-01-01T18:53:22.000Z');
Insert into APPS.XXINV_INTEGRATION_INTERFACE (INTERFACE_ID,UPDATE_DATE) values ('empUpdate','2017-02-02T12:00:03.159Z');
Insert into APPS.XXINV_INTEGRATION_INTERFACE (INTERFACE_ID,UPDATE_DATE) values ('empAssignmentUpdate','2016-12-28T09:40:59.509Z');
Insert into APPS.XXINV_INTEGRATION_INTERFACE (INTERFACE_ID,UPDATE_DATE) values ('empTerminate','2017-02-02T12:00:01.063Z');
Insert into APPS.XXINV_INTEGRATION_INTERFACE (INTERFACE_ID,UPDATE_DATE) values ('newhireUpdate','2017-02-02T12:00:03.644Z');



--------------------------------------------------------
--  DDL for Table XXINV_INTEGRATION_PERSON
--------------------------------------------------------

  CREATE TABLE "APPS"."XXINV_INTEGRATION_PERSON" 
   (	"PERSON_ID" VARCHAR2(30 BYTE), 
	"PERSON_NUMBER" VARCHAR2(100 BYTE), 
	"EMPLOYEE_CODE" VARCHAR2(100 BYTE), 
	"TALEO_EMP_ID" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
REM INSERTING into APPS.XXINV_INTEGRATION_PERSON
SET DEFINE OFF;
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values (null,null,null,'3540');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values (null,null,null,'3542');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values (null,null,null,'3543');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values (null,null,null,'3540');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values (null,null,null,'3541');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values (null,null,null,'3543');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('PER_3544','PERSON3544','Neeel Nithin','3544');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('PER_3548','PERSON3548','Eveline Tom','3548');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('100000001869813','PERSON3549','Michel Lilly','3549');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('PER_3554','PERSON3554','Vinil Vijay','3554');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('PER_13530','Test3530','Ramesh Rohan','3530');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('PER3_3529','Test33529','Maria Johnson','3529');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('PER3_3530','Test33530','Ramesh Rohan','3530');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('PER3_3532','STUDENT_PERSON3532','John Martin','3532');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('PER_3553','PERSON3553','Sylvia Solan','3553');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('100000001200401','PERSON3538','David Jones','3538');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('PER3_35322','STUDENT_PERSON35322','John2 Martin2','35322');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('PER4_35333','STUDENT_PERSON35333','Millan2 Lee2','35333');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('PER_35333','PERSON35333','Millan2 Lee2','35333');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('PER_3533','PERSON3533','Millan1 Lee1','3533');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('PER_35335','PERSON35335','Millantest Leetest','35335');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('PER_35336','PERSON35336','Millantest6 Leetest6','35336');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('100000001189651','PERSON35346','Roneltest6 Nixontest6','35346');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('PER4_35343','STUDENT_PERSON35343','Ronel2 Nixon2','35343');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('100000001199206','PERSON3535','Antony Goel','3535');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('100000001190179','PERSON3537','Nimal Neo','3537');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values (null,null,null,'3539');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values (null,null,null,'3539');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values (null,null,null,'3537');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values (null,null,null,'3538');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values (null,null,null,'3539');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('300000013164220','1000725','xx','3524');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('300000013165168','1000726','xx','3525');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('100000000401918','587','xx','2831');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('300000012497049','1000679','xx','3491');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('300000011687077','1000643','xx','3502');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('100000000401900','561','xx','2829');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('100000000401427','113','Goehl','3067');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('300000010779456','1000459','Victoria','3428');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('300000012985638','1000721','Roy','3522');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('300000012988301','1000722','Sahu, Manoj','3506');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('100000000401375','103','Seeger, Joseph','2857');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('100000000401597','428','Solorzano, Sylvia','2949');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('100000000769593','1000428','Wu, Camille','3415');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('100000000401917','585','Yama','3406');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('100000000834133','1000484','Raja','3528');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('300000012795323','1000717','xx','3507');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('PER3529','Test3529','Maria Johnson','3529');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('PER_3552','PERSON3552','Roshan Renoy','3552');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('PER_3551','PERSON3551','Vijay Prabhu','3551');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('PER_13529','Test3529','Maria Johnson','3529');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('PER3_35323','STUDENT_PERSON35323','John2 Martin2','35323');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('PER4_35323','STUDENT_PERSON35323','John2 Martin2','35323');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('PER_3550','PERSON3550','Noyal Nelson','3550');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('PER_3534','PERSON3534','Ronel Nixon','3534');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('100000001433261','PERSON3545','Garry Logan','3545');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('PER_3546','PERSON3546','Nagaraju Munigala','3546');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('PER_3547','PERSON3547','Stefania Chicca','3547');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('PER2_3529','Test23529','Maria Johnson','3529');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('PER_3540','PERSON3540','Larry Page','3540');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('PER_3541','PERSON3541','Henry Smith','3541');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('PER_3542','PERSON3542','Juan Chang','3542');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('PER_33529','Test3529','Maria Johnson','3529');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('PER1_3529','Test13529','Maria Johnson','3529');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('PER_3535','PERSON3535','Antony Goel','3535');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('PER_3537','PERSON3537','Nimal Neo','3537');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('PER_3539','PERSON3539','Stephanie Malatesta','3539');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values (null,null,null,'3535');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values (null,null,null,'3537');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values (null,null,null,'3539');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('PER_3543','PERSON3543','Peter Smith','3543');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values (null,null,null,'3540');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values (null,null,null,'3542');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values (null,null,null,'3543');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('PER_35501','PERSON35501','Noyal1 Nelson1','35501');
Insert into APPS.XXINV_INTEGRATION_PERSON (PERSON_ID,PERSON_NUMBER,EMPLOYEE_CODE,TALEO_EMP_ID) values ('PER_35502','PERSON35502','Noyal2 Nelson2','35502');
