package com.invensense.model.workrelations;

public class F_WORK_RELATIONSHIP_VO {

	private String ACCEPTED_TERMINATION_DATE;
	private String ACTION_OCCURRENCE_ID;
	private String ACTUAL_TERMINATION_DATE;
	private String ADJUSTED_SVC_DATE;
	private String BUSINESS_GROUP_ID;
	private String DATE_EMPLOYEE_DATA_VERIFIED;
	private String DATE_START;
	private String FAST_PATH_EMPLOYEE;
	private String LAST_WORKING_DATE;
	private String LEGAL_ENTITY_ID;
	private String LEGISLATION_CODE;
	private String NOTIFIED_TERMINATION_DATE;
	private String ON_MILITARY_SERVICE;
	private String ORIGINAL_DATE_OF_HIRE;
	private String PERIOD_OF_SERVICE_ID;
	private String PERIOD_TYPE;
	private String PERSON_ID;
	private String PRIMARY_FLAG;
	private String PROJECTED_TERMINATION_DATE;
	private String REHIRE_AUTHORIZOR;
	private String REHIRE_REASON;
	private String REHIRE_RECOMMENDATION;
	private String TERMINATION_ACCEPTED_PERSON_ID;
	private String WORKER_NUMBER;
	private String COMMENTS;
	private String REHIRE_AUTHORIZER_PERSON_ID;
	private String FT_ALTERNATE_REC;
	private String FT_ALTERNATE_KEY;
	public String getACCEPTED_TERMINATION_DATE() {
		return ACCEPTED_TERMINATION_DATE;
	}
	public void setACCEPTED_TERMINATION_DATE(String aCCEPTED_TERMINATION_DATE) {
		ACCEPTED_TERMINATION_DATE = aCCEPTED_TERMINATION_DATE;
	}
	public String getACTION_OCCURRENCE_ID() {
		return ACTION_OCCURRENCE_ID;
	}
	public void setACTION_OCCURRENCE_ID(String aCTION_OCCURRENCE_ID) {
		ACTION_OCCURRENCE_ID = aCTION_OCCURRENCE_ID;
	}
	public String getACTUAL_TERMINATION_DATE() {
		return ACTUAL_TERMINATION_DATE;
	}
	public void setACTUAL_TERMINATION_DATE(String aCTUAL_TERMINATION_DATE) {
		ACTUAL_TERMINATION_DATE = aCTUAL_TERMINATION_DATE;
	}
	public String getADJUSTED_SVC_DATE() {
		return ADJUSTED_SVC_DATE;
	}
	public void setADJUSTED_SVC_DATE(String aDJUSTED_SVC_DATE) {
		ADJUSTED_SVC_DATE = aDJUSTED_SVC_DATE;
	}
	public String getBUSINESS_GROUP_ID() {
		return BUSINESS_GROUP_ID;
	}
	public void setBUSINESS_GROUP_ID(String bUSINESS_GROUP_ID) {
		BUSINESS_GROUP_ID = bUSINESS_GROUP_ID;
	}
	public String getDATE_EMPLOYEE_DATA_VERIFIED() {
		return DATE_EMPLOYEE_DATA_VERIFIED;
	}
	public void setDATE_EMPLOYEE_DATA_VERIFIED(String dATE_EMPLOYEE_DATA_VERIFIED) {
		DATE_EMPLOYEE_DATA_VERIFIED = dATE_EMPLOYEE_DATA_VERIFIED;
	}
	public String getDATE_START() {
		return DATE_START;
	}
	public void setDATE_START(String dATE_START) {
		DATE_START = dATE_START;
	}
	public String getFAST_PATH_EMPLOYEE() {
		return FAST_PATH_EMPLOYEE;
	}
	public void setFAST_PATH_EMPLOYEE(String fAST_PATH_EMPLOYEE) {
		FAST_PATH_EMPLOYEE = fAST_PATH_EMPLOYEE;
	}
	public String getLAST_WORKING_DATE() {
		return LAST_WORKING_DATE;
	}
	public void setLAST_WORKING_DATE(String lAST_WORKING_DATE) {
		LAST_WORKING_DATE = lAST_WORKING_DATE;
	}
	public String getLEGAL_ENTITY_ID() {
		return LEGAL_ENTITY_ID;
	}
	public void setLEGAL_ENTITY_ID(String lEGAL_ENTITY_ID) {
		LEGAL_ENTITY_ID = lEGAL_ENTITY_ID;
	}
	public String getLEGISLATION_CODE() {
		return LEGISLATION_CODE;
	}
	public void setLEGISLATION_CODE(String lEGISLATION_CODE) {
		LEGISLATION_CODE = lEGISLATION_CODE;
	}
	public String getNOTIFIED_TERMINATION_DATE() {
		return NOTIFIED_TERMINATION_DATE;
	}
	public void setNOTIFIED_TERMINATION_DATE(String nOTIFIED_TERMINATION_DATE) {
		NOTIFIED_TERMINATION_DATE = nOTIFIED_TERMINATION_DATE;
	}
	public String getON_MILITARY_SERVICE() {
		return ON_MILITARY_SERVICE;
	}
	public void setON_MILITARY_SERVICE(String oN_MILITARY_SERVICE) {
		ON_MILITARY_SERVICE = oN_MILITARY_SERVICE;
	}
	public String getORIGINAL_DATE_OF_HIRE() {
		return ORIGINAL_DATE_OF_HIRE;
	}
	public void setORIGINAL_DATE_OF_HIRE(String oRIGINAL_DATE_OF_HIRE) {
		ORIGINAL_DATE_OF_HIRE = oRIGINAL_DATE_OF_HIRE;
	}
	public String getPERIOD_OF_SERVICE_ID() {
		return PERIOD_OF_SERVICE_ID;
	}
	public void setPERIOD_OF_SERVICE_ID(String pERIOD_OF_SERVICE_ID) {
		PERIOD_OF_SERVICE_ID = pERIOD_OF_SERVICE_ID;
	}
	public String getPERIOD_TYPE() {
		return PERIOD_TYPE;
	}
	public void setPERIOD_TYPE(String pERIOD_TYPE) {
		PERIOD_TYPE = pERIOD_TYPE;
	}
	public String getPERSON_ID() {
		return PERSON_ID;
	}
	public void setPERSON_ID(String pERSON_ID) {
		PERSON_ID = pERSON_ID;
	}
	public String getPRIMARY_FLAG() {
		return PRIMARY_FLAG;
	}
	public void setPRIMARY_FLAG(String pRIMARY_FLAG) {
		PRIMARY_FLAG = pRIMARY_FLAG;
	}
	public String getPROJECTED_TERMINATION_DATE() {
		return PROJECTED_TERMINATION_DATE;
	}
	public void setPROJECTED_TERMINATION_DATE(String pROJECTED_TERMINATION_DATE) {
		PROJECTED_TERMINATION_DATE = pROJECTED_TERMINATION_DATE;
	}
	public String getREHIRE_AUTHORIZOR() {
		return REHIRE_AUTHORIZOR;
	}
	public void setREHIRE_AUTHORIZOR(String rEHIRE_AUTHORIZOR) {
		REHIRE_AUTHORIZOR = rEHIRE_AUTHORIZOR;
	}
	public String getREHIRE_REASON() {
		return REHIRE_REASON;
	}
	public void setREHIRE_REASON(String rEHIRE_REASON) {
		REHIRE_REASON = rEHIRE_REASON;
	}
	public String getREHIRE_RECOMMENDATION() {
		return REHIRE_RECOMMENDATION;
	}
	public void setREHIRE_RECOMMENDATION(String rEHIRE_RECOMMENDATION) {
		REHIRE_RECOMMENDATION = rEHIRE_RECOMMENDATION;
	}
	public String getTERMINATION_ACCEPTED_PERSON_ID() {
		return TERMINATION_ACCEPTED_PERSON_ID;
	}
	public void setTERMINATION_ACCEPTED_PERSON_ID(String tERMINATION_ACCEPTED_PERSON_ID) {
		TERMINATION_ACCEPTED_PERSON_ID = tERMINATION_ACCEPTED_PERSON_ID;
	}
	public String getWORKER_NUMBER() {
		return WORKER_NUMBER;
	}
	public void setWORKER_NUMBER(String wORKER_NUMBER) {
		WORKER_NUMBER = wORKER_NUMBER;
	}
	public String getCOMMENTS() {
		return COMMENTS;
	}
	public void setCOMMENTS(String cOMMENTS) {
		COMMENTS = cOMMENTS;
	}
	public String getREHIRE_AUTHORIZER_PERSON_ID() {
		return REHIRE_AUTHORIZER_PERSON_ID;
	}
	public void setREHIRE_AUTHORIZER_PERSON_ID(String rEHIRE_AUTHORIZER_PERSON_ID) {
		REHIRE_AUTHORIZER_PERSON_ID = rEHIRE_AUTHORIZER_PERSON_ID;
	}
	public String getFT_ALTERNATE_REC() {
		return FT_ALTERNATE_REC;
	}
	public void setFT_ALTERNATE_REC(String fT_ALTERNATE_REC) {
		FT_ALTERNATE_REC = fT_ALTERNATE_REC;
	}
	public String getFT_ALTERNATE_KEY() {
		return FT_ALTERNATE_KEY;
	}
	public void setFT_ALTERNATE_KEY(String fT_ALTERNATE_KEY) {
		FT_ALTERNATE_KEY = fT_ALTERNATE_KEY;
	}
	
	public String toDelimitedString() {
		return ACCEPTED_TERMINATION_DATE + "|" + ACTION_OCCURRENCE_ID + "|" + ACTUAL_TERMINATION_DATE + "|"
				+ ADJUSTED_SVC_DATE + "|" + BUSINESS_GROUP_ID + "|" + DATE_EMPLOYEE_DATA_VERIFIED + "|" + DATE_START
				+ "|" + FAST_PATH_EMPLOYEE + "|" + LAST_WORKING_DATE + "|" + LEGAL_ENTITY_ID + "|" + LEGISLATION_CODE
				+ "|" + NOTIFIED_TERMINATION_DATE + "|" + ON_MILITARY_SERVICE + "|" + ORIGINAL_DATE_OF_HIRE + "|"
				+ PERIOD_OF_SERVICE_ID + "|" + PERIOD_TYPE + "|" + PERSON_ID + "|" + PRIMARY_FLAG + "|"
				+ PROJECTED_TERMINATION_DATE + "|" + REHIRE_AUTHORIZOR + "|" + REHIRE_REASON + "|"
				+ REHIRE_RECOMMENDATION + "|" + TERMINATION_ACCEPTED_PERSON_ID + "|" + WORKER_NUMBER + "|" + COMMENTS
				+ "|" + REHIRE_AUTHORIZER_PERSON_ID + "|" + FT_ALTERNATE_REC + "|" + FT_ALTERNATE_KEY ;
	}

}
